namespace CryptoParser.Models
{
   public struct CVBData
   {
      public readonly CVBType CVB;
      public readonly Bank[] Banks;
      public readonly Currency[] Currencies;

      public CVBData(CVBType cvb, Bank[] banks, Currency[] currencies)
      {
         CVB = cvb;
         Banks = banks;
         Currencies = currencies;
      }
   }

   public static class Constants
   {
      private static readonly Bank[] _binanceBanks = { Bank.Tinkoff, Bank.Sberbank, Bank.Raiffaisen, Bank.QIWI, Bank.YandexMoney };
      private static readonly Bank[] _OKXBanks =     { Bank.Tinkoff, Bank.Sberbank, Bank.Raiffaisen, Bank.QIWI, Bank.YandexMoney };
      private static readonly Bank[] _HuobiBanks =   { Bank.Tinkoff, Bank.Sberbank, Bank.Raiffaisen, Bank.QIWI, Bank.YandexMoney };
      private static readonly Currency[] _binanceCurrencies = { Currency.USDT, Currency.BTC, Currency.BUSD, Currency.BNB, Currency.ETH };
      private static readonly Currency[] _OKXCurrencies =     { Currency.USDT, Currency.BTC,                              Currency.ETH };
      private static readonly Currency[] _HuobiCurrencies =   { Currency.USDT, Currency.BTC,                              Currency.ETH };
      public static readonly string TimePos = "Общая информация:E:4";
      public static readonly string SettingsPos = "Общая информация:F:4";
      public static readonly Dictionary<string, string> SimpleTablesRanges = new()
      { 
         { "Rates|Binance|",                    "Общая информация:B:11"       },
         { "MarketRates|Binance|",              "Общая информация:B:18"       },
         { "Convert|Binance|",                  "Общая информация:B:21"       },
         { "Rates|OKX|",                        "Общая информация:B:31"       },
         { "MarketRates|OKX|",                  "Общая информация:B:36"       },
         { "Convert|OKX|",                      "Общая информация:B:39"       },
         { "Rates|Huobi|",                      "Общая информация:B:47"       },
         { "MarketRates|Huobi|",                "Общая информация:B:52"       },
         { "Convert|Huobi|",                    "Общая информация:B:55"       },

         { "BankOnlyMaker|Binance|Tinkoff",     "Binance простые связки:K:4"  },
         { "BankOnlyMaker|Binance|Sberbank",    "Binance простые связки:K:12" },
         { "BankOnlyMaker|Binance|Raiffaisen",  "Binance простые связки:K:20" },
         { "BankOnlyMaker|Binance|QIWI",        "Binance простые связки:K:28" },
         { "BankOnlyMaker|Binance|YandexMoney", "Binance простые связки:K:36" },
         { "CurrencyOnlyMaker|Binance|USDT",    "Binance простые связки:C:4"  },
         { "CurrencyOnlyMaker|Binance|BTC",     "Binance простые связки:C:12" },
         { "CurrencyOnlyMaker|Binance|BUSD",    "Binance простые связки:C:20" },
         { "CurrencyOnlyMaker|Binance|BNB",     "Binance простые связки:C:28" },
         { "CurrencyOnlyMaker|Binance|ETH",     "Binance простые связки:C:36" },

         { "BankWithTaker|Binance|Tinkoff",     "Binance простые связки:K:45" },
         { "BankWithTaker|Binance|Sberbank",    "Binance простые связки:K:53" },
         { "BankWithTaker|Binance|Raiffaisen",  "Binance простые связки:K:61" },
         { "BankWithTaker|Binance|QIWI",        "Binance простые связки:K:69" },
         { "BankWithTaker|Binance|YandexMoney", "Binance простые связки:K:77" },
         { "CurrencyWithTaker|Binance|USDT",    "Binance простые связки:C:45" },
         { "CurrencyWithTaker|Binance|BTC",     "Binance простые связки:C:53" },
         { "CurrencyWithTaker|Binance|BUSD",    "Binance простые связки:C:61" },
         { "CurrencyWithTaker|Binance|BNB",     "Binance простые связки:C:69" },
         { "CurrencyWithTaker|Binance|ETH",     "Binance простые связки:C:77" },

         { "BankOnlyMaker|OKX|Tinkoff",         "OKX простые связки:K:4"      },
         { "BankOnlyMaker|OKX|Sberbank",        "OKX простые связки:K:10"     },
         { "BankOnlyMaker|OKX|Raiffaisen",      "OKX простые связки:K:16"     },
         { "BankOnlyMaker|OKX|QIWI",            "OKX простые связки:K:22"     },
         { "BankOnlyMaker|OKX|YandexMoney",     "OKX простые связки:K:28"     },
         { "CurrencyOnlyMaker|OKX|USDT",        "OKX простые связки:C:4"      },
         { "CurrencyOnlyMaker|OKX|BTC",         "OKX простые связки:C:12"     },
         { "CurrencyOnlyMaker|OKX|ETH",         "OKX простые связки:C:20"     },

         { "BankOnlyMaker|Huobi|Tinkoff",       "Huobi простые связки:K:4"      },
         { "BankOnlyMaker|Huobi|Sberbank",      "Huobi простые связки:K:10"     },
         { "BankOnlyMaker|Huobi|Raiffaisen",    "Huobi простые связки:K:16"     },
         { "BankOnlyMaker|Huobi|QIWI",          "Huobi простые связки:K:22"     },
         { "BankOnlyMaker|Huobi|YandexMoney",   "Huobi простые связки:K:28"     },
         { "CurrencyOnlyMaker|Huobi|USDT",      "Huobi простые связки:C:4"      },
         { "CurrencyOnlyMaker|Huobi|BTC",       "Huobi простые связки:C:12"     },
         { "CurrencyOnlyMaker|Huobi|ETH",       "Huobi простые связки:C:20"     },
      };

      public static readonly Dictionary<string, string> HardTablesRanges = new()
      {
         { "HardLinksOnlyMaker|Binance|Binance|Tinkoff|USDT",           "Binance сложные связки:D:4"   },
         { "HardLinksOnlyMaker|Binance|Binance|Tinkoff|BTC",            "Binance сложные связки:M:4"   },
         { "HardLinksOnlyMaker|Binance|Binance|Tinkoff|BUSD",           "Binance сложные связки:D:12"  },
         { "HardLinksOnlyMaker|Binance|Binance|Tinkoff|BNB",            "Binance сложные связки:M:12"  },
         { "HardLinksOnlyMaker|Binance|Binance|Tinkoff|ETH",            "Binance сложные связки:D:20"  },
         { "HardLinksOnlyMaker|Binance|Binance|Sberbank|USDT",           "Binance сложные связки:D:30"  },
         { "HardLinksOnlyMaker|Binance|Binance|Sberbank|BTC",            "Binance сложные связки:M:30"  },
         { "HardLinksOnlyMaker|Binance|Binance|Sberbank|BUSD",           "Binance сложные связки:D:38"  },
         { "HardLinksOnlyMaker|Binance|Binance|Sberbank|BNB",            "Binance сложные связки:M:38"  },
         { "HardLinksOnlyMaker|Binance|Binance|Sberbank|ETH",            "Binance сложные связки:D:46"  },
         { "HardLinksOnlyMaker|Binance|Binance|Raiffaisen|USDT",       "Binance сложные связки:D:56"  },
         { "HardLinksOnlyMaker|Binance|Binance|Raiffaisen|BTC",        "Binance сложные связки:M:56"  },
         { "HardLinksOnlyMaker|Binance|Binance|Raiffaisen|BUSD",       "Binance сложные связки:D:64"  },
         { "HardLinksOnlyMaker|Binance|Binance|Raiffaisen|BNB",        "Binance сложные связки:M:64"  },
         { "HardLinksOnlyMaker|Binance|Binance|Raiffaisen|ETH",        "Binance сложные связки:D:72"  },
         { "HardLinksOnlyMaker|Binance|Binance|QIWI|USDT",                 "Binance сложные связки:D:82"  },
         { "HardLinksOnlyMaker|Binance|Binance|QIWI|BTC",                  "Binance сложные связки:M:82"  },
         { "HardLinksOnlyMaker|Binance|Binance|QIWI|BUSD",                 "Binance сложные связки:D:90"  },
         { "HardLinksOnlyMaker|Binance|Binance|QIWI|BNB",                  "Binance сложные связки:M:90"  },
         { "HardLinksOnlyMaker|Binance|Binance|QIWI|ETH",                  "Binance сложные связки:D:98"  },
         { "HardLinksOnlyMaker|Binance|Binance|YandexMoney|USDT",       "Binance сложные связки:D:108" },
         { "HardLinksOnlyMaker|Binance|Binance|YandexMoney|BTC",        "Binance сложные связки:M:108" },
         { "HardLinksOnlyMaker|Binance|Binance|YandexMoney|BUSD",       "Binance сложные связки:D:116" },
         { "HardLinksOnlyMaker|Binance|Binance|YandexMoney|BNB",        "Binance сложные связки:M:116" },
         { "HardLinksOnlyMaker|Binance|Binance|YandexMoney|ETH",        "Binance сложные связки:D:124" },

         { "HardLinksWithTaker|Binance|Binance|Tinkoff|USDT",           "Binance сложные связки:D:133" },
         { "HardLinksWithTaker|Binance|Binance|Tinkoff|BTC",            "Binance сложные связки:M:133" },
         { "HardLinksWithTaker|Binance|Binance|Tinkoff|BUSD",           "Binance сложные связки:D:141" },
         { "HardLinksWithTaker|Binance|Binance|Tinkoff|BNB",            "Binance сложные связки:M:141" },
         { "HardLinksWithTaker|Binance|Binance|Tinkoff|ETH",            "Binance сложные связки:D:149" },
         { "HardLinksWithTaker|Binance|Binance|Sberbank|USDT",           "Binance сложные связки:D:159" },
         { "HardLinksWithTaker|Binance|Binance|Sberbank|BTC",            "Binance сложные связки:M:159" },
         { "HardLinksWithTaker|Binance|Binance|Sberbank|BUSD",           "Binance сложные связки:D:167" },
         { "HardLinksWithTaker|Binance|Binance|Sberbank|BNB",            "Binance сложные связки:M:167" },
         { "HardLinksWithTaker|Binance|Binance|Sberbank|ETH",            "Binance сложные связки:D:175" },
         { "HardLinksWithTaker|Binance|Binance|Raiffaisen|USDT",       "Binance сложные связки:D:185" },
         { "HardLinksWithTaker|Binance|Binance|Raiffaisen|BTC",        "Binance сложные связки:M:185" },
         { "HardLinksWithTaker|Binance|Binance|Raiffaisen|BUSD",       "Binance сложные связки:D:193" },
         { "HardLinksWithTaker|Binance|Binance|Raiffaisen|BNB",        "Binance сложные связки:M:193" },
         { "HardLinksWithTaker|Binance|Binance|Raiffaisen|ETH",        "Binance сложные связки:D:201" },
         { "HardLinksWithTaker|Binance|Binance|QIWI|USDT",                 "Binance сложные связки:D:211" },
         { "HardLinksWithTaker|Binance|Binance|QIWI|BTC",                  "Binance сложные связки:M:211" },
         { "HardLinksWithTaker|Binance|Binance|QIWI|BUSD",                 "Binance сложные связки:D:219" },
         { "HardLinksWithTaker|Binance|Binance|QIWI|BNB",                  "Binance сложные связки:M:219" },
         { "HardLinksWithTaker|Binance|Binance|QIWI|ETH",                  "Binance сложные связки:D:227" },
         { "HardLinksWithTaker|Binance|Binance|YandexMoney|USDT",       "Binance сложные связки:D:237" },
         { "HardLinksWithTaker|Binance|Binance|YandexMoney|BTC",        "Binance сложные связки:M:237" },
         { "HardLinksWithTaker|Binance|Binance|YandexMoney|BUSD",       "Binance сложные связки:D:245" },
         { "HardLinksWithTaker|Binance|Binance|YandexMoney|BNB",        "Binance сложные связки:M:245" },
         { "HardLinksWithTaker|Binance|Binance|YandexMoney|ETH",        "Binance сложные связки:D:253" },

         { "HardLinksOnlyMaker|OKX|OKX|Tinkoff|USDT",                      "OKX сложные связки:D:4"       },
         { "HardLinksOnlyMaker|OKX|OKX|Tinkoff|BTC",                       "OKX сложные связки:K:4"       },
         { "HardLinksOnlyMaker|OKX|OKX|Tinkoff|ETH",                       "OKX сложные связки:R:4"       },
         { "HardLinksOnlyMaker|OKX|OKX|Sberbank|USDT",                      "OKX сложные связки:D:14"      },
         { "HardLinksOnlyMaker|OKX|OKX|Sberbank|BTC",                       "OKX сложные связки:K:14"      },
         { "HardLinksOnlyMaker|OKX|OKX|Sberbank|ETH",                       "OKX сложные связки:R:14"      },
         { "HardLinksOnlyMaker|OKX|OKX|Raiffaisen|USDT",                   "OKX сложные связки:D:24"      },
         { "HardLinksOnlyMaker|OKX|OKX|Raiffaisen|BTC",                    "OKX сложные связки:K:24"      },
         { "HardLinksOnlyMaker|OKX|OKX|Raiffaisen|ETH",                    "OKX сложные связки:R:24"      },
         { "HardLinksOnlyMaker|OKX|OKX|QIWI|USDT",                         "OKX сложные связки:D:34"      },
         { "HardLinksOnlyMaker|OKX|OKX|QIWI|BTC",                          "OKX сложные связки:K:34"      },
         { "HardLinksOnlyMaker|OKX|OKX|QIWI|ETH",                          "OKX сложные связки:R:34"      },
         { "HardLinksOnlyMaker|OKX|OKX|YandexMoney|USDT",                 "OKX сложные связки:D:44"      },
         { "HardLinksOnlyMaker|OKX|OKX|YandexMoney|BTC",                  "OKX сложные связки:K:44"      },
         { "HardLinksOnlyMaker|OKX|OKX|YandexMoney|ETH",                  "OKX сложные связки:R:44"      },

         { "HardLinksOnlyMaker|Huobi|Huobi|Tinkoff|USDT",                      "Huobi сложные связки:D:4"       },
         { "HardLinksOnlyMaker|Huobi|Huobi|Tinkoff|BTC",                       "Huobi сложные связки:K:4"       },
         { "HardLinksOnlyMaker|Huobi|Huobi|Tinkoff|ETH",                       "Huobi сложные связки:R:4"       },
         { "HardLinksOnlyMaker|Huobi|Huobi|Sberbank|USDT",                      "Huobi сложные связки:D:14"      },
         { "HardLinksOnlyMaker|Huobi|Huobi|Sberbank|BTC",                       "Huobi сложные связки:K:14"      },
         { "HardLinksOnlyMaker|Huobi|Huobi|Sberbank|ETH",                       "Huobi сложные связки:R:14"      },
         { "HardLinksOnlyMaker|Huobi|Huobi|Raiffaisen|USDT",                   "Huobi сложные связки:D:24"      },
         { "HardLinksOnlyMaker|Huobi|Huobi|Raiffaisen|BTC",                    "Huobi сложные связки:K:24"      },
         { "HardLinksOnlyMaker|Huobi|Huobi|Raiffaisen|ETH",                    "Huobi сложные связки:R:24"      },
         { "HardLinksOnlyMaker|Huobi|Huobi|QIWI|USDT",                         "Huobi сложные связки:D:34"      },
         { "HardLinksOnlyMaker|Huobi|Huobi|QIWI|BTC",                          "Huobi сложные связки:K:34"      },
         { "HardLinksOnlyMaker|Huobi|Huobi|QIWI|ETH",                          "Huobi сложные связки:R:34"      },
         { "HardLinksOnlyMaker|Huobi|Huobi|YandexMoney|USDT",                 "Huobi сложные связки:D:44"      },
         { "HardLinksOnlyMaker|Huobi|Huobi|YandexMoney|BTC",                  "Huobi сложные связки:K:44"      },
         { "HardLinksOnlyMaker|Huobi|Huobi|YandexMoney|ETH",                  "Huobi сложные связки:R:44"      },

         { "HardLinksOnlyMaker|Binance|OKX|Tinkoff|USDT",                  "Binance->OKX:D:4"             },
         { "HardLinksOnlyMaker|Binance|OKX|Tinkoff|BTC",                   "Binance->OKX:K:4"             },
         { "HardLinksOnlyMaker|Binance|OKX|Tinkoff|BUSD",                  "Binance->OKX:R:4"             },
         { "HardLinksOnlyMaker|Binance|OKX|Tinkoff|BNB",                   "Binance->OKX:D:12"            },
         { "HardLinksOnlyMaker|Binance|OKX|Tinkoff|ETH",                   "Binance->OKX:K:12"            },
         { "HardLinksOnlyMaker|Binance|OKX|Sberbank|USDT",                  "Binance->OKX:D:22"            },
         { "HardLinksOnlyMaker|Binance|OKX|Sberbank|BTC",                   "Binance->OKX:K:22"            },
         { "HardLinksOnlyMaker|Binance|OKX|Sberbank|BUSD",                  "Binance->OKX:R:22"            },
         { "HardLinksOnlyMaker|Binance|OKX|Sberbank|BNB",                   "Binance->OKX:D:30"            },
         { "HardLinksOnlyMaker|Binance|OKX|Sberbank|ETH",                   "Binance->OKX:K:30"            },
         { "HardLinksOnlyMaker|Binance|OKX|Raiffaisen|USDT",               "Binance->OKX:D:40"            },
         { "HardLinksOnlyMaker|Binance|OKX|Raiffaisen|BTC",                "Binance->OKX:K:40"            },
         { "HardLinksOnlyMaker|Binance|OKX|Raiffaisen|BUSD",               "Binance->OKX:R:40"            },
         { "HardLinksOnlyMaker|Binance|OKX|Raiffaisen|BNB",                "Binance->OKX:D:48"            },
         { "HardLinksOnlyMaker|Binance|OKX|Raiffaisen|ETH",                "Binance->OKX:K:48"            },
         { "HardLinksOnlyMaker|Binance|OKX|QIWI|USDT",                     "Binance->OKX:D:58"            },
         { "HardLinksOnlyMaker|Binance|OKX|QIWI|BTC",                      "Binance->OKX:K:58"            },
         { "HardLinksOnlyMaker|Binance|OKX|QIWI|BUSD",                     "Binance->OKX:R:58"            },
         { "HardLinksOnlyMaker|Binance|OKX|QIWI|BNB",                      "Binance->OKX:D:66"            },
         { "HardLinksOnlyMaker|Binance|OKX|QIWI|ETH",                      "Binance->OKX:K:66"            },
         { "HardLinksOnlyMaker|Binance|OKX|YandexMoney|USDT",             "Binance->OKX:D:76"            },
         { "HardLinksOnlyMaker|Binance|OKX|YandexMoney|BTC",              "Binance->OKX:K:76"            },
         { "HardLinksOnlyMaker|Binance|OKX|YandexMoney|BUSD",             "Binance->OKX:R:76"            },
         { "HardLinksOnlyMaker|Binance|OKX|YandexMoney|BNB",              "Binance->OKX:D:84"            },
         { "HardLinksOnlyMaker|Binance|OKX|YandexMoney|ETH",              "Binance->OKX:K:84"            },

         { "HardLinksWithTaker|Binance|OKX|Tinkoff|USDT",                  "Binance->OKX:D:93"            },
         { "HardLinksWithTaker|Binance|OKX|Tinkoff|BTC",                   "Binance->OKX:K:93"            },
         { "HardLinksWithTaker|Binance|OKX|Tinkoff|BUSD",                  "Binance->OKX:R:93"            },
         { "HardLinksWithTaker|Binance|OKX|Tinkoff|BNB",                   "Binance->OKX:D:101"           },
         { "HardLinksWithTaker|Binance|OKX|Tinkoff|ETH",                   "Binance->OKX:K:101"           },
         { "HardLinksWithTaker|Binance|OKX|Sberbank|USDT",                  "Binance->OKX:D:111"           },
         { "HardLinksWithTaker|Binance|OKX|Sberbank|BTC",                   "Binance->OKX:K:111"           },
         { "HardLinksWithTaker|Binance|OKX|Sberbank|BUSD",                  "Binance->OKX:R:111"           },
         { "HardLinksWithTaker|Binance|OKX|Sberbank|BNB",                   "Binance->OKX:D:119"           },
         { "HardLinksWithTaker|Binance|OKX|Sberbank|ETH",                   "Binance->OKX:K:119"           },
         { "HardLinksWithTaker|Binance|OKX|Raiffaisen|USDT",               "Binance->OKX:D:129"           },
         { "HardLinksWithTaker|Binance|OKX|Raiffaisen|BTC",                "Binance->OKX:K:129"           },
         { "HardLinksWithTaker|Binance|OKX|Raiffaisen|BUSD",               "Binance->OKX:R:129"           },
         { "HardLinksWithTaker|Binance|OKX|Raiffaisen|BNB",                "Binance->OKX:D:137"           },
         { "HardLinksWithTaker|Binance|OKX|Raiffaisen|ETH",                "Binance->OKX:K:137"           },
         { "HardLinksWithTaker|Binance|OKX|QIWI|USDT",                     "Binance->OKX:D:147"           },
         { "HardLinksWithTaker|Binance|OKX|QIWI|BTC",                      "Binance->OKX:K:147"           },
         { "HardLinksWithTaker|Binance|OKX|QIWI|BUSD",                     "Binance->OKX:R:147"           },
         { "HardLinksWithTaker|Binance|OKX|QIWI|BNB",                      "Binance->OKX:D:155"           },
         { "HardLinksWithTaker|Binance|OKX|QIWI|ETH",                      "Binance->OKX:K:155"           },
         { "HardLinksWithTaker|Binance|OKX|YandexMoney|USDT",             "Binance->OKX:D:165"           },
         { "HardLinksWithTaker|Binance|OKX|YandexMoney|BTC",              "Binance->OKX:K:165"           },
         { "HardLinksWithTaker|Binance|OKX|YandexMoney|BUSD",             "Binance->OKX:R:165"           },
         { "HardLinksWithTaker|Binance|OKX|YandexMoney|BNB",              "Binance->OKX:D:173"           },
         { "HardLinksWithTaker|Binance|OKX|YandexMoney|ETH",              "Binance->OKX:K:173"           },

         { "HardLinksOnlyMaker|Binance|Huobi|Tinkoff|USDT",                  "Binance->Huobi:D:4"             },
         { "HardLinksOnlyMaker|Binance|Huobi|Tinkoff|BTC",                   "Binance->Huobi:K:4"             },
         { "HardLinksOnlyMaker|Binance|Huobi|Tinkoff|BUSD",                  "Binance->Huobi:R:4"             },
         { "HardLinksOnlyMaker|Binance|Huobi|Tinkoff|BNB",                   "Binance->Huobi:D:12"            },
         { "HardLinksOnlyMaker|Binance|Huobi|Tinkoff|ETH",                   "Binance->Huobi:K:12"            },
         { "HardLinksOnlyMaker|Binance|Huobi|Sberbank|USDT",                  "Binance->Huobi:D:22"            },
         { "HardLinksOnlyMaker|Binance|Huobi|Sberbank|BTC",                   "Binance->Huobi:K:22"            },
         { "HardLinksOnlyMaker|Binance|Huobi|Sberbank|BUSD",                  "Binance->Huobi:R:22"            },
         { "HardLinksOnlyMaker|Binance|Huobi|Sberbank|BNB",                   "Binance->Huobi:D:30"            },
         { "HardLinksOnlyMaker|Binance|Huobi|Sberbank|ETH",                   "Binance->Huobi:K:30"            },
         { "HardLinksOnlyMaker|Binance|Huobi|Raiffaisen|USDT",               "Binance->Huobi:D:40"            },
         { "HardLinksOnlyMaker|Binance|Huobi|Raiffaisen|BTC",                "Binance->Huobi:K:40"            },
         { "HardLinksOnlyMaker|Binance|Huobi|Raiffaisen|BUSD",               "Binance->Huobi:R:40"            },
         { "HardLinksOnlyMaker|Binance|Huobi|Raiffaisen|BNB",                "Binance->Huobi:D:48"            },
         { "HardLinksOnlyMaker|Binance|Huobi|Raiffaisen|ETH",                "Binance->Huobi:K:48"            },
         { "HardLinksOnlyMaker|Binance|Huobi|QIWI|USDT",                     "Binance->Huobi:D:58"            },
         { "HardLinksOnlyMaker|Binance|Huobi|QIWI|BTC",                      "Binance->Huobi:K:58"            },
         { "HardLinksOnlyMaker|Binance|Huobi|QIWI|BUSD",                     "Binance->Huobi:R:58"            },
         { "HardLinksOnlyMaker|Binance|Huobi|QIWI|BNB",                      "Binance->Huobi:D:66"            },
         { "HardLinksOnlyMaker|Binance|Huobi|QIWI|ETH",                      "Binance->Huobi:K:66"            },
         { "HardLinksOnlyMaker|Binance|Huobi|YandexMoney|USDT",             "Binance->Huobi:D:76"            },
         { "HardLinksOnlyMaker|Binance|Huobi|YandexMoney|BTC",              "Binance->Huobi:K:76"            },
         { "HardLinksOnlyMaker|Binance|Huobi|YandexMoney|BUSD",             "Binance->Huobi:R:76"            },
         { "HardLinksOnlyMaker|Binance|Huobi|YandexMoney|BNB",              "Binance->Huobi:D:84"            },
         { "HardLinksOnlyMaker|Binance|Huobi|YandexMoney|ETH",              "Binance->Huobi:K:84"            },

         { "HardLinksWithTaker|Binance|Huobi|Tinkoff|USDT",                  "Binance->Huobi:D:93"            },
         { "HardLinksWithTaker|Binance|Huobi|Tinkoff|BTC",                   "Binance->Huobi:K:93"            },
         { "HardLinksWithTaker|Binance|Huobi|Tinkoff|BUSD",                  "Binance->Huobi:R:93"            },
         { "HardLinksWithTaker|Binance|Huobi|Tinkoff|BNB",                   "Binance->Huobi:D:101"           },
         { "HardLinksWithTaker|Binance|Huobi|Tinkoff|ETH",                   "Binance->Huobi:K:101"           },
         { "HardLinksWithTaker|Binance|Huobi|Sberbank|USDT",                  "Binance->Huobi:D:111"           },
         { "HardLinksWithTaker|Binance|Huobi|Sberbank|BTC",                   "Binance->Huobi:K:111"           },
         { "HardLinksWithTaker|Binance|Huobi|Sberbank|BUSD",                  "Binance->Huobi:R:111"           },
         { "HardLinksWithTaker|Binance|Huobi|Sberbank|BNB",                   "Binance->Huobi:D:119"           },
         { "HardLinksWithTaker|Binance|Huobi|Sberbank|ETH",                   "Binance->Huobi:K:119"           },
         { "HardLinksWithTaker|Binance|Huobi|Raiffaisen|USDT",               "Binance->Huobi:D:129"           },
         { "HardLinksWithTaker|Binance|Huobi|Raiffaisen|BTC",                "Binance->Huobi:K:129"           },
         { "HardLinksWithTaker|Binance|Huobi|Raiffaisen|BUSD",               "Binance->Huobi:R:129"           },
         { "HardLinksWithTaker|Binance|Huobi|Raiffaisen|BNB",                "Binance->Huobi:D:137"           },
         { "HardLinksWithTaker|Binance|Huobi|Raiffaisen|ETH",                "Binance->Huobi:K:137"           },
         { "HardLinksWithTaker|Binance|Huobi|QIWI|USDT",                     "Binance->Huobi:D:147"           },
         { "HardLinksWithTaker|Binance|Huobi|QIWI|BTC",                      "Binance->Huobi:K:147"           },
         { "HardLinksWithTaker|Binance|Huobi|QIWI|BUSD",                     "Binance->Huobi:R:147"           },
         { "HardLinksWithTaker|Binance|Huobi|QIWI|BNB",                      "Binance->Huobi:D:155"           },
         { "HardLinksWithTaker|Binance|Huobi|QIWI|ETH",                      "Binance->Huobi:K:155"           },
         { "HardLinksWithTaker|Binance|Huobi|YandexMoney|USDT",             "Binance->Huobi:D:165"           },
         { "HardLinksWithTaker|Binance|Huobi|YandexMoney|BTC",              "Binance->Huobi:K:165"           },
         { "HardLinksWithTaker|Binance|Huobi|YandexMoney|BUSD",             "Binance->Huobi:R:165"           },
         { "HardLinksWithTaker|Binance|Huobi|YandexMoney|BNB",              "Binance->Huobi:D:173"           },
         { "HardLinksWithTaker|Binance|Huobi|YandexMoney|ETH",              "Binance->Huobi:K:173"           },

         { "HardLinksOnlyMaker|OKX|Binance|Tinkoff|USDT",               "OKX->Binance:D:4"             },
         { "HardLinksOnlyMaker|OKX|Binance|Tinkoff|BTC",                "OKX->Binance:M:4"             },
         { "HardLinksOnlyMaker|OKX|Binance|Tinkoff|ETH",                "OKX->Binance:D:12"            },
         { "HardLinksOnlyMaker|OKX|Binance|Sberbank|USDT",               "OKX->Binance:D:22"            },
         { "HardLinksOnlyMaker|OKX|Binance|Sberbank|BTC",                "OKX->Binance:M:22"            },
         { "HardLinksOnlyMaker|OKX|Binance|Sberbank|ETH",                "OKX->Binance:D:30"            },
         { "HardLinksOnlyMaker|OKX|Binance|Raiffaisen|USDT",           "OKX->Binance:D:40"            },
         { "HardLinksOnlyMaker|OKX|Binance|Raiffaisen|BTC",            "OKX->Binance:M:40"            },
         { "HardLinksOnlyMaker|OKX|Binance|Raiffaisen|ETH",            "OKX->Binance:D:48"            },
         { "HardLinksOnlyMaker|OKX|Binance|QIWI|USDT",                     "OKX->Binance:D:58"            },
         { "HardLinksOnlyMaker|OKX|Binance|QIWI|BTC",                      "OKX->Binance:M:58"            },
         { "HardLinksOnlyMaker|OKX|Binance|QIWI|ETH",                      "OKX->Binance:D:66"            },
         { "HardLinksOnlyMaker|OKX|Binance|YandexMoney|USDT",           "OKX->Binance:D:76"            },
         { "HardLinksOnlyMaker|OKX|Binance|YandexMoney|BTC",            "OKX->Binance:M:76"            },
         { "HardLinksOnlyMaker|OKX|Binance|YandexMoney|ETH",            "OKX->Binance:D:84"            },

         { "HardLinksOnlyMaker|OKX|Huobi|Tinkoff|USDT",                      "OKX->Huobi:D:4"       },
         { "HardLinksOnlyMaker|OKX|Huobi|Tinkoff|BTC",                       "OKX->Huobi:K:4"       },
         { "HardLinksOnlyMaker|OKX|Huobi|Tinkoff|ETH",                       "OKX->Huobi:R:4"       },
         { "HardLinksOnlyMaker|OKX|Huobi|Sberbank|USDT",                      "OKX->Huobi:D:14"      },
         { "HardLinksOnlyMaker|OKX|Huobi|Sberbank|BTC",                       "OKX->Huobi:K:14"      },
         { "HardLinksOnlyMaker|OKX|Huobi|Sberbank|ETH",                       "OKX->Huobi:R:14"      },
         { "HardLinksOnlyMaker|OKX|Huobi|Raiffaisen|USDT",                   "OKX->Huobi:D:24"      },
         { "HardLinksOnlyMaker|OKX|Huobi|Raiffaisen|BTC",                    "OKX->Huobi:K:24"      },
         { "HardLinksOnlyMaker|OKX|Huobi|Raiffaisen|ETH",                    "OKX->Huobi:R:24"      },
         { "HardLinksOnlyMaker|OKX|Huobi|QIWI|USDT",                         "OKX->Huobi:D:34"      },
         { "HardLinksOnlyMaker|OKX|Huobi|QIWI|BTC",                          "OKX->Huobi:K:34"      },
         { "HardLinksOnlyMaker|OKX|Huobi|QIWI|ETH",                          "OKX->Huobi:R:34"      },
         { "HardLinksOnlyMaker|OKX|Huobi|YandexMoney|USDT",                 "OKX->Huobi:D:44"      },
         { "HardLinksOnlyMaker|OKX|Huobi|YandexMoney|BTC",                  "OKX->Huobi:K:44"      },
         { "HardLinksOnlyMaker|OKX|Huobi|YandexMoney|ETH",                  "OKX->Huobi:R:44"      },

         { "HardLinksOnlyMaker|Huobi|Binance|Tinkoff|USDT",               "Huobi->Binance:D:4"             },
         { "HardLinksOnlyMaker|Huobi|Binance|Tinkoff|BTC",                "Huobi->Binance:M:4"             },
         { "HardLinksOnlyMaker|Huobi|Binance|Tinkoff|ETH",                "Huobi->Binance:D:12"            },
         { "HardLinksOnlyMaker|Huobi|Binance|Sberbank|USDT",               "Huobi->Binance:D:22"            },
         { "HardLinksOnlyMaker|Huobi|Binance|Sberbank|BTC",                "Huobi->Binance:M:22"            },
         { "HardLinksOnlyMaker|Huobi|Binance|Sberbank|ETH",                "Huobi->Binance:D:30"            },
         { "HardLinksOnlyMaker|Huobi|Binance|Raiffaisen|USDT",           "Huobi->Binance:D:40"            },
         { "HardLinksOnlyMaker|Huobi|Binance|Raiffaisen|BTC",            "Huobi->Binance:M:40"            },
         { "HardLinksOnlyMaker|Huobi|Binance|Raiffaisen|ETH",            "Huobi->Binance:D:48"            },
         { "HardLinksOnlyMaker|Huobi|Binance|QIWI|USDT",                     "Huobi->Binance:D:58"            },
         { "HardLinksOnlyMaker|Huobi|Binance|QIWI|BTC",                      "Huobi->Binance:M:58"            },
         { "HardLinksOnlyMaker|Huobi|Binance|QIWI|ETH",                      "Huobi->Binance:D:66"            },
         { "HardLinksOnlyMaker|Huobi|Binance|YandexMoney|USDT",           "Huobi->Binance:D:76"            },
         { "HardLinksOnlyMaker|Huobi|Binance|YandexMoney|BTC",            "Huobi->Binance:M:76"            },
         { "HardLinksOnlyMaker|Huobi|Binance|YandexMoney|ETH",            "Huobi->Binance:D:84"            },

         { "HardLinksOnlyMaker|Huobi|OKX|Tinkoff|USDT",                      "Huobi->OKX:D:4"       },
         { "HardLinksOnlyMaker|Huobi|OKX|Tinkoff|BTC",                       "Huobi->OKX:K:4"       },
         { "HardLinksOnlyMaker|Huobi|OKX|Tinkoff|ETH",                       "Huobi->OKX:R:4"       },
         { "HardLinksOnlyMaker|Huobi|OKX|Sberbank|USDT",                      "Huobi->OKX:D:14"      },
         { "HardLinksOnlyMaker|Huobi|OKX|Sberbank|BTC",                       "Huobi->OKX:K:14"      },
         { "HardLinksOnlyMaker|Huobi|OKX|Sberbank|ETH",                       "Huobi->OKX:R:14"      },
         { "HardLinksOnlyMaker|Huobi|OKX|Raiffaisen|USDT",                   "Huobi->OKX:D:24"      },
         { "HardLinksOnlyMaker|Huobi|OKX|Raiffaisen|BTC",                    "Huobi->OKX:K:24"      },
         { "HardLinksOnlyMaker|Huobi|OKX|Raiffaisen|ETH",                    "Huobi->OKX:R:24"      },
         { "HardLinksOnlyMaker|Huobi|OKX|QIWI|USDT",                         "Huobi->OKX:D:34"      },
         { "HardLinksOnlyMaker|Huobi|OKX|QIWI|BTC",                          "Huobi->OKX:K:34"      },
         { "HardLinksOnlyMaker|Huobi|OKX|QIWI|ETH",                          "Huobi->OKX:R:34"      },
         { "HardLinksOnlyMaker|Huobi|OKX|YandexMoney|USDT",                 "Huobi->OKX:D:44"      },
         { "HardLinksOnlyMaker|Huobi|OKX|YandexMoney|BTC",                  "Huobi->OKX:K:44"      },
         { "HardLinksOnlyMaker|Huobi|OKX|YandexMoney|ETH",                  "Huobi->OKX:R:44"      },
      };

      public static CVBData GetCVBData(CVBType cvb)
      {
         switch (cvb)
         {
            case CVBType.Binance: return new CVBData(CVBType.Binance, _binanceBanks, _binanceCurrencies);
            case CVBType.OKX:     return new CVBData(CVBType.OKX, _OKXBanks, _OKXCurrencies);
            case CVBType.Huobi:   return new CVBData(CVBType.Huobi, _HuobiBanks, _HuobiCurrencies);
            default:              return new CVBData();
         }
      }
   }
}
